"use client";

// The methods paragraph and citation for the result on screen.
//
// Collapsed by default: it is long, and it is wanted at writing-up time rather
// than while exploring. The text is generated by lib/methods.ts from the spec
// and the table, so it describes the query that actually ran — including, for a
// stitched series, which file supplied which years and which rates were
// computed here rather than published by CDC.

import { useState } from "react";
import type { QuerySpec, ResultTable } from "@/lib/wonder/types";
import { buildMethods, methodsForClipboard } from "@/lib/methods";

export default function MethodsPanel({
  spec,
  table,
}: {
  spec: QuerySpec;
  table: ResultTable;
}) {
  const [open, setOpen] = useState(false);
  const [copied, setCopied] = useState(false);

  // Regenerated on each render rather than memoised: it is a few string joins,
  // and the accession date should be the moment the user copies it.
  const m = buildMethods(spec, table);

  const copy = async () => {
    try {
      await navigator.clipboard.writeText(methodsForClipboard(m));
      setCopied(true);
      setTimeout(() => setCopied(false), 1800);
    } catch {
      // Clipboard access can be refused; the text is on screen to select.
      setCopied(false);
    }
  };

  return (
    <div className="rounded-lg border border-slate-200 bg-white">
      <div className="flex items-center justify-between px-3 py-2">
        <button
          type="button"
          onClick={() => setOpen((o) => !o)}
          className="text-xs font-medium text-blue-600 hover:underline"
          aria-expanded={open}
        >
          {open ? "Hide" : "Show"} methods &amp; citation
        </button>
        {open && (
          <button
            type="button"
            onClick={copy}
            className="rounded-lg border border-slate-300 px-3 py-1 text-xs font-medium text-slate-700 hover:bg-slate-50"
          >
            {copied ? "Copied" : "Copy all"}
          </button>
        )}
      </div>

      {open && (
        <div className="space-y-3 border-t border-slate-200 px-3 py-3 text-xs leading-relaxed text-slate-700">
          <div>
            <p className="mb-1 font-semibold uppercase tracking-wide text-slate-500">Methods</p>
            <p>{m.methods}</p>
          </div>
          <div>
            <p className="mb-1 font-semibold uppercase tracking-wide text-slate-500">
              {m.citations.length === 1 ? "Citation" : "Citations"}
            </p>
            <ol className="list-decimal space-y-1 pl-5">
              {m.citations.map((c, i) => (
                <li key={i}>{c}</li>
              ))}
            </ol>
          </div>
          <p className="text-[11px] text-slate-400">
            Generated from the query that produced this table, accessed {m.accessed}. CDC
            WONDER&apos;s API does not return a citation, so this follows the format its web
            interface prints — worth checking once against your journal&apos;s requirements.
          </p>
        </div>
      )}
    </div>
  );
}
